/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "secondary-container": "#fed488",
        "tertiary-container": "#1b365d",
        "secondary-fixed-dim": "#e9c176",
        "secondary-fixed": "#ffdea5",
        "background": "#faf9f6",
        "on-error-container": "#93000a",
        "tertiary": "#002046",
        "on-secondary-container": "#785a1a",
        "surface-tint": "#465f88",
        "outline": "#74777f",
        "on-tertiary-container": "#87a0cd",
        "on-tertiary-fixed": "#001b3d",
        "inverse-surface": "#2f312f",
        "secondary": "#775a19",
        "primary-fixed": "#d6e3ff",
        "on-tertiary": "#ffffff",
        "inverse-primary": "#aec7f7",
        "surface-container-low": "#f4f3f1",
        "tertiary-fixed-dim": "#aec7f7",
        "on-tertiary-fixed-variant": "#2e476f",
        "surface-container": "#efeeeb",
        "on-secondary": "#ffffff",
        "inverse-on-surface": "#f2f1ee",
        "primary-fixed-dim": "#aec7f7",
        "surface-bright": "#faf9f6",
        "on-primary-fixed-variant": "#2e476f",
        "on-secondary-fixed-variant": "#5d4201",
        "on-error": "#ffffff",
        "on-primary-fixed": "#001b3d",
        "surface-container-highest": "#e3e2e0",
        "surface-container-high": "#e9e8e5",
        "on-primary": "#ffffff",
        "error": "#ba1a1a",
        "primary-container": "#1b365d",
        "primary": "#002046",
        "surface-container-lowest": "#ffffff",
        "surface": "#faf9f6",
        "error-container": "#ffdad6",
        "surface-dim": "#dbdad7",
        "surface-variant": "#e3e2e0",
        "on-secondary-fixed": "#261900",
        "on-surface-variant": "#44474e",
        "on-primary-container": "#87a0cd",
        "on-surface": "#1a1c1a",
        "on-background": "#1a1c1a",
        "tertiary-fixed": "#d6e3ff",
        "outline-variant": "#c4c6cf"
      },
      fontFamily: {
        headline: ["Inter", "sans-serif"],
        body: ["Lexend", "sans-serif"],
        label: ["Inter", "sans-serif"]
      },
      boxShadow: {
        'ambient': '0 8px 24px -4px rgba(26, 28, 26, 0.06)',
        'premium': '0 20px 40px -10px rgba(0, 0, 0, 0.1)',
      },
      borderRadius: {
        'none': '0',
        'sm': '0.25rem',
        'DEFAULT': '0.5rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        'full': '9999px',
      },
      backgroundImage: {
        'hero-gradient': 'linear-gradient(135deg, #002046 0%, #1b365d 100%)',
      }
    },
  },
  plugins: [],
}
