"""add_room_url_to_clases

Revision ID: 088dc0c77aac
Revises: 4f9618f8d22a
Create Date: 2026-04-21 11:50:43.633473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '088dc0c77aac'
down_revision: Union[str, Sequence[str], None] = '4f9618f8d22a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clases', sa.Column('room_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clases', 'room_url')
    # ### end Alembic commands ###
